apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: hotstar
        image: sanjeevrisbud/hotstar-clone:latest
        ports:
        - containerPort: 3000  # Port your application listens on
